spring:
  datasource:
    url: jdbc:mysql://localhost:3306/well-bridge?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect


server:
  port: 8083
  adress: 192.186.1.101

jwt:
  secret: RandomSecretKeyIsNothingHappensInContradictionToNatureOnlyInContradictionToWhatWeKnowOfItXFilesS04E5
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.wellbridge.wellbridge: DEBUG

app:
  firebase-configuration-file: well-bridge-firebase-adminsdk.json


mail:
  host: smtp.gmail.com
  port: 587
  username: franklindjoumessi576@gmail.com
  password: bomolytxsacgoipc
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true


